name: Branch Name Check

on:
  push:
    branches:
      - '*'

jobs:
  branch-name-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Validate branch name
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release|task)/ ]]; then
          echo "Branch name '$BRANCH_NAME' does not follow the naming conventions."
          echo "Branch names should start with 'feature/', 'bugfix/', 'hotfix/', 'release/', or 'task/'."
          exit 1
        fi
